name: "Setup Poetry"
inputs:
  python:
    default: "3.13"

runs:
  using: composite
  shell: bash
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}
        cache: "poetry"
    - run: curl -sSL https://install.python-poetry.org | python -
    - run: poetry config virtualenvs.in-project true
    - uses: actions/cache@v4
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: poetry
