name: Workflow artefact
on:
  workflow_dispatch:

jobs:
  testing_phase:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            repository: 'tldr-pages/tldr-python-client'
            ref: '3.4.0'
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - run: python -m pip install -r requirements.txt
        - run: python -m pip install -U pytest pytest-html
        - run: pytest tests/ --html=report.html
        - uses: actions/upload-artifact@v4
          with:
            name: pytest-report
            path: report.html

        - uses: actions/download-artifact@v4
          with:
            name: pytest-report
            path: .
