name: 3 Job
on: push


jobs:
  first_job:
    name: "1 job"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ceci est le premier job"
  second_job:
    name: "2 job"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ceci est le second job"
  third_job:
    name: "3 job"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ceci est le troisième job"