name: "Poetry app"
on:
  workflow_dispatch:

jobs:
  poetry_app:
    runs-on: runner
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/setup_poetry
        with:
          python: "3.10"
      - run: poetry install
      - run: pytest tests/
      - run: poetry build