name: Workflow Dispatch
on:
  workflow_dispatch:
      inputs:
        choice:
          required: true
          type: choice
          options:
            - jedi
            - sith
            - rebel
        username:
          type: string
          required: true
        level:
          type: string
          required: true

jobs:
  player_infos:
    name: "Player Infos"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Le joueur ${{ inputs.username }} est de niveau ${{ inputs.level }} et joue un ${{ inputs.choice }}."
