name: Workflow Checkout
on: workflow_dispatch

jobs:
  checkout:
    name: "Print README"
    runs-on: ubuntu-latest
    steps:
      - name: "Load source code"
        uses: action/checkout@v4
      - name: "print readme"
        run: "cat README.md"