name: Workflow poetry_build
on:
  workflow_dispatch:

jobs:
  poetry_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install
